language: objective-c
osx_image: xcode6.4
script:
    - xcodebuild -project thumborurl.xcodeproj -scheme thumborurl -sdk iphonesimulator -configuration Debug -PBXBuildsContinueAfterErrors=0 ACTIVE_ARCH_ONLY=0 build test
